pipeline {
  agent any
  environment {
    PROJECT_DIR = "project-3-cicd-docker-deploy"
    IMAGE_NAME = "ismailclouds/project-3-pipeline-docker-new"
    IMAGE_TAG = "${BUILD_NUMBER}"
    CONTAINER_NAME = "project-3-pipeline-docker-new"
    EMAIL_TO = "venkatesangunaraj@gmail.com"
    DOCKER_CREDENTIALS = "dockerhub-credentials"
  }
  stages {
    stage("Build") {
      steps {
        dir("${PROJECT_DIR}") {
          sh '''
            echo "Build started!"
            echo "Branch: ${GIT_BRANCH}"
            echo "Build Number: ${BUILD_NUMBER}"
            npm install
          '''
        }
      }
    }
    stage("Test") {
      steps {
        dir("${PROJECT_DIR}") {
          sh "npm test"
        }
      }
    }
    stage("Docker Build") {
      steps {
        dir("${PROJECT_DIR}") {
          sh """
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
          """
        }
      }
    }
    stage("Push to Docker Hub") {
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${DOCKER_CREDENTIALS}",
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
            docker push ${IMAGE_NAME}:latest
          '''
        }
      }
    }
    stage("Docker Deploy (Local)") {
      steps {
        sh '''
            docker stop ${CONTAINER_NAME} || true
            docker rm ${CONTAINER_NAME} || true
            docker run -d \
              --name ${CONTAINER_NAME} \
              -p 3003:3003 \
              ${IMAGE_NAME}:${IMAGE_TAG}
        '''
      }
    }
  }
  post {
    success {
      mail(
        to: "${EMAIL_TO}",
        subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
        body: "Project 3 CI/CD succeeded.\nJob: ${env.JOB_NAME}\nBuild: #${env.BUILD_NUMBER}\nURL: ${env.BUILD_URL}"
      )
    }
    failure {
      mail(
        to:
