pipeline {
  agent any
  environment {
    PROJECT_DIR = "project-4-multibranch-pipeline"
    IMAGE_NAME = "venkatesan004/project-4-multibranch-pipeline"
    IMAGE_TAG = "${BUILD_NUMBER}"
    CONTAINER_NAME = "project-4-multibranch-pipeline"
    EMAIL_TO = "venkatesangunaraj@gmail.com"
    DOCKER_CREDENTIALS = "dockerhub-credentials"
  }
  stages {
    stage("Build") {
      steps {
        dir("${PROJECT_DIR}") {
          sh '''
            echo "Build started!"
            echo "Branch: ${GIT_BRANCH}"
            echo "Build Number: ${BUILD_NUMBER}"
            npm install
          '''
        }
      }
    }
    stage("Test") {
      steps {
        dir("${PROJECT_DIR}") {
          sh "npm test"
        }
      }
    }
    // 🔹 Only for main
    stage("Docker Build") {
      when {
}
